from typing import Any, Literal

from pydantic import BaseModel, Field

from app.autoresearcher.pipeline import AutoresearchDomainImprovementPipeline
from app.core.runtime import AgentRuntime
from app.db.repositories import InMemoryRepository
from app.domains.registry import DomainRegistry
from app.obsidian.note_writer import ObsidianNoteWriter
from app.rag.ingestion import DocumentIngestor
from app.rag.retriever import InMemoryRetriever
from app.tools.registry import ToolRegistry


UseCaseKind = Literal[
    "agent_run",
    "rag_ingest_search",
    "autoresearch_plan",
    "obsidian_note",
]


class UseCaseDefinition(BaseModel):
    use_case_id: str
    title: str
    kind: UseCaseKind
    description: str
    expected_result: str
    request_payload: dict[str, Any] = Field(default_factory=dict)
    follow_up_endpoints: list[str] = Field(default_factory=list)


USE_CASES: dict[str, UseCaseDefinition] = {
    "research-agent-run": UseCaseDefinition(
        use_case_id="research-agent-run",
        title="Run the Research Literature Agent",
        kind="agent_run",
        description="Validates agent contract loading, input validation, planning, model gateway output, trace artifacts, and eval records.",
        expected_result="A completed run for research.literature_researcher with steps, tool calls, artifacts, and evaluations.",
        request_payload={
            "agent_id": "research.literature_researcher",
            "input_payload": {
                "research_question": "Agentic research governance for domain-specific AI systems"
            },
        },
        follow_up_endpoints=[
            "GET /runs/{run_id}",
            "GET /runs/{run_id}/steps",
            "GET /runs/{run_id}/artifacts",
            "GET /evals/{run_id}",
        ],
    ),
    "cybersecurity-sigma-run": UseCaseDefinition(
        use_case_id="cybersecurity-sigma-run",
        title="Run the Cybersecurity Sigma Agent",
        kind="agent_run",
        description="Validates cybersecurity domain contracts and Sigma-specific output schema fields.",
        expected_result="A completed run with summary, sigma_rule, evidence, false_positive_analysis, and confidence_score.",
        request_payload={
            "agent_id": "cybersecurity.sigma_rule_agent",
            "input_payload": {
                "threat_description": "Suspicious PowerShell execution with encoded command",
                "target_platform": "windows",
                "log_sources": ["process_creation"],
            },
        },
        follow_up_endpoints=[
            "GET /runs/{run_id}",
            "GET /runs/{run_id}/tool-calls",
            "GET /runs/{run_id}/artifacts",
        ],
    ),
    "rag-ingest-search": UseCaseDefinition(
        use_case_id="rag-ingest-search",
        title="Ingest and Search a RAG Document",
        kind="rag_ingest_search",
        description="Validates document ingestion, chunking, metadata propagation, lexical retrieval, and citation IDs.",
        expected_result="A document_id, chunk_count, and at least one search result with citation_id.",
        request_payload={
            "title": "Sigma Behavioral Vectors",
            "content": "Sigma rules can represent behavioral threat vectors for detection engineering.",
            "metadata": {"source_type": "local", "domain_id": "cybersecurity"},
            "query": "behavioral threat vectors",
            "limit": 5,
        },
    ),
    "autoresearch-domain-plan": UseCaseDefinition(
        use_case_id="autoresearch-domain-plan",
        title="Generate an Autoresearch Domain Improvement Plan",
        kind="autoresearch_plan",
        description="Validates Karpathy-style program.md generation for measurable domain asset improvement.",
        expected_result="A plan containing program.md, experiment_plan.json, measurement_rubric.json, and improvement_backlog.md.",
        request_payload={
            "domain_id": "cybersecurity",
            "budget_minutes": 30,
            "primary_metric": "eval_pass_rate",
            "targets": [],
        },
    ),
    "obsidian-note-stub": UseCaseDefinition(
        use_case_id="obsidian-note-stub",
        title="Create an Obsidian Note",
        kind="obsidian_note",
        description="Validates frontmatter generation and path sanitization for local-first note output.",
        expected_result="A note response with path, Markdown frontmatter, content, and disabled-mode stub status unless Obsidian is enabled.",
        request_payload={
            "title": "NeuroAgent Test Note",
            "body": "This note was generated by the use case catalog.",
            "folder": "00_Inbox",
        },
    ),
}


class UseCaseRunner:
    def __init__(
        self,
        repository: InMemoryRepository,
        domain_registry: DomainRegistry,
        tool_registry: ToolRegistry,
        ingestor: DocumentIngestor,
    ) -> None:
        self.repository = repository
        self.domain_registry = domain_registry
        self.tool_registry = tool_registry
        self.ingestor = ingestor

    def list_use_cases(self) -> list[UseCaseDefinition]:
        return list(USE_CASES.values())

    def get_use_case(self, use_case_id: str) -> UseCaseDefinition | None:
        return USE_CASES.get(use_case_id)

    def run(self, use_case_id: str) -> dict[str, Any] | None:
        use_case = self.get_use_case(use_case_id)
        if use_case is None:
            return None
        payload = use_case.request_payload
        if use_case.kind == "agent_run":
            run = AgentRuntime(
                self.domain_registry,
                self.tool_registry,
                self.repository,
            ).run_agent(payload["agent_id"], payload["input_payload"])
            return {"use_case": use_case.model_dump(), "result": run}
        if use_case.kind == "rag_ingest_search":
            ingest_result = self.ingestor.ingest(
                payload["title"],
                payload["content"],
                payload["metadata"],
            )
            search_results = InMemoryRetriever(self.ingestor).search(payload["query"], payload["limit"])
            return {
                "use_case": use_case.model_dump(),
                "result": {"ingest": ingest_result, "search_results": search_results},
            }
        if use_case.kind == "autoresearch_plan":
            plan = AutoresearchDomainImprovementPipeline().plan(
                domain_id=payload["domain_id"],
                targets=[],
                budget_minutes=payload["budget_minutes"],
                primary_metric=payload["primary_metric"],
            )
            return {"use_case": use_case.model_dump(), "result": plan.model_dump()}
        if use_case.kind == "obsidian_note":
            note = ObsidianNoteWriter().write_note(
                payload["title"],
                payload["body"],
                payload["folder"],
            )
            return {"use_case": use_case.model_dump(), "result": note}
        return None
